name: Docker Build And Push To Docker Hub

on:
  push:
    branches:
#      - master
    tags:
      - V*

jobs:
  build:
    name: Build Proxy Panel
    runs-on: ubuntu-18.04
    steps:
      - name: Git Checkout Code
        uses: actions/checkout@v1
        id: git_checkout

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          push: true
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_REPO }}
          tag_with_ref: true
          tag_with_sha: true
          tags: latest
